---
- name: Generate virtual baremetal MAC addresses
  hosts: sushy-libvirt
  gather_facts: false
  tasks:
    - name: Write hosts
      block:
        - name: Create address dictionary
          set_fact:
            bikolla_mac_addresses: "{{ bikolla_mac_addresses | combine( { item: '52:54:00' | community.general.random_mac} ) }}"
          vars:
            bikolla_mac_addresses: {}
          delegate_to: localhost
          with_items: "{{ play_hosts }}"

        - name: Write mac addresses file
          copy:
            content: '{{ {"bikolla_mac_addresses": bikolla_mac_addresses} | to_nice_yaml }}'
            dest: "{{ kayobe_env_config_path }}/bikolla-mac-addresses.yml"
          delegate_to: localhost
      run_once: true

    - name: debug
      debug:
        msg: "{{ bikolla_mac_addresses[inventory_hostname] }}"
