---
- name: Provision baremetal instances
  hosts: baremetal-compute
  gather_facts: false
  tasks:
    - name: Get baremetal port metadata
      openstack.cloud.baremetal_port_info:
        node: "{{ inventory_hostname }}"
      delegate_to: localhost
      register: baremetal
      run_once: true

    - name: debug
      debug:
        msg: "{{ baremetal.ports[0] }}"
      delegate_to: localhost

    - name: Deploy instances
      openstack.cloud.baremetal_node_action:
        name: "{{ inventory_hostname }}"
        config_drive: "{{ ironic_config_drive }}"
        instance_info: "{{ ironic_instance_info }}"
      delegate_to: localhost
