- name: Setup Sushy Emulator
  hosts: localhost
  become: true
  gather_facts: false
  tasks:
    - name: Enable Rocky devel repository
      community.general.dnf_config_manager:
        name: devel
        state: enabled
    
    - name: Install package dependencies
      ansible.builtin.dnf:
        name:
          - qemu-kvm
          - libvirt
          - libvirt-devel
          - python3-devel
        state: present

    - name: Start and enable the QEMU service
      ansible.builtin.systemd_service:
        name: virtqemud
        state: started
        enabled: true

    - name: Start and enable the virtual stroage service
      ansible.builtin.systemd_service:
        name: virtstoraged
        state: started
        enabled: true

    - name: Start and enable the virtual network service
      ansible.builtin.systemd_service:
        name: virtnetworkd
        state: started
        enabled: true

    - name: Create Sushy virtualenv
      ansible.builtin.pip:
        name:
          - libvirt-python
          - sushy-tools
        virtualenv: /opt/kayobe/venvs/sushy
        virtualenv_command: python3.12 -m venv

    - name: Template Sushy service unit file
      ansible.builtin.template:
        src: "{{ kayobe_env_config_path }}/ansible/sushyemud.service.j2"
        dest: "/etc/systemd/system/sushyemud.service"

    - name: Start and enable the Sushy Emulator service
      ansible.builtin.systemd_service:
        name: sushyemud
        state: started
        enabled: true
